name: Lint and Format Code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Run HTMLHint for HTML linting
      - name: Run HTMLHint
        uses: wzieba/HTMLHint-action@v2
        with:
          config: '.htmlhintrc'  # Optional: path to custom HTMLHint config

      # Run Stylelint for CSS linting
      - name: Run Stylelint
        uses: stylelint-action/ci-action@v3
        with:
          configFile: '.stylelintrc'

      # Run ESLint for JavaScript linting
      - name: Run ESLint
        uses: eslint-action/action@v2
        with:
          eslint_config: '.eslintrc.json'

      # Run Prettier to format code
      - name: Run Prettier
        uses: esbenp/prettier-action@v2
        with:
          prettier_config: '.prettierrc'

      # Run accessibility checks (optional)
      - name: Run Axe Accessibility Tests
        uses: dequelabs/axe-action@v2
        with:
          url: 'https://example.com'

      # Run Super Linter for general linting (optional)
      - name: Run Super Linter
        uses: github/super-linter@v4
        with:
          run: true
